package com.weatherplanner.app;

import com.google.ai.client.generativeai.GenerativeModel;
import com.google.ai.client.generativeai.java.GenerativeModelFutures;
import com.google.ai.client.generativeai.type.Content;
import com.google.ai.client.generativeai.type.GenerateContentResponse;
import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.MoreExecutors;

import android.util.Log;

/**
 * ThemeGenerator uses Gemini LLM to generate UI color themes based on natural language prompts.
 *
 * This utility class provides asynchronous theme generation by sending user prompts to the
 * Gemini API, which returns a cohesive set of colors that are validated for readability
 * and accessibility (WCAG AA contrast standards).
 *
 * Usage example:
 * <pre>
 * ThemeGenerator.generateTheme(apiKey, "summer beach", new ThemeCallback() {
 *     public void onThemeGenerated(ThemeSpec theme) {
 *         // Apply theme colors
 *     }
 *     public void onError(Exception e) {
 *         // Handle error
 *     }
 * });
 * </pre>
 */
public class ThemeGenerator {
    static final String TAG = "ThemeGenerator";

    /**
     * Data class representing a UI theme specification.
     * Contains hex color values for various UI elements to ensure a cohesive visual design.
     */
    public static class ThemeSpec {
        /** Background color for main content areas (hex format: #RRGGBB) */
        public String backgroundColor;

        /** Primary text color that contrasts with backgroundColor (hex format: #RRGGBB) */
        public String textColor;

        /** Accent color for highlights and emphasis (hex format: #RRGGBB) */
        public String accentColor;

        /** Button background color (hex format: #RRGGBB) */
        public String buttonColor;

        /** Toolbar/AppBar background color (hex format: #RRGGBB) */
        public String toolbarColor;
    }

    /**
     * Callback interface for asynchronous theme generation.
     * Implementations receive either a generated theme or an error.
     */
    public interface ThemeCallback {
        /**
         * Called when a theme has been successfully generated by the LLM.
         *
         * @param theme The generated ThemeSpec containing color values for UI elements
         */
        void onThemeGenerated(ThemeSpec theme);

        /**
         * Called when theme generation fails due to API errors, network issues, or invalid responses.
         *
         * @param e Exception describing the failure (e.g., network error, API key invalid, parsing error)
         */
        void onError(Exception e);
    }

    /**
     * Generates a UI theme based on natural language description using Gemini LLM.
     * Theme generation is asynchronous and results are returned via callback.
     *
     * @param apiKey Gemini API key for authentication
     * @param prompt Natural language description of desired theme (e.g., "summer beach")
     * @param callback Callback to receive generated theme or error
     */
    public static void generateTheme(String apiKey, String prompt, ThemeCallback callback) {
        if (apiKey == null || apiKey.isEmpty()) {
            Log.w(TAG, "API key missing; returning default demo theme.");
            ThemeSpec theme = new ThemeSpec();
            theme.backgroundColor = "#F7FAFC";
            theme.textColor = "#1A202C";
            theme.accentColor = "#2563EB";
            theme.buttonColor = "#10B981";
            theme.toolbarColor = "#1F2937";
            callback.onThemeGenerated(theme);
            return;
        }

        GenerativeModel gm = new GenerativeModel(GeminiModels.FAST_TEXT_MODEL, apiKey);
        GenerativeModelFutures model = GenerativeModelFutures.from(gm);

        String createPrompt = "You are an expert UI/UX designer. Create a HIGHLY READABLE and VISUALLY STRIKING Android app theme based on: '" + prompt +
                "'.\n\nCRITICAL REQUIREMENTS:\n" +
                "1. backgroundColor and textColor MUST have high contrast (WCAG AA standard)\n" +
                "2. If background is light (white/yellow/cream), text MUST be dark (black/dark gray)\n" +
                "3. If background is dark (black/navy/purple), text MUST be light (white/light gray)\n" +
                "4. buttonColor must be DISTINCT and VISIBLE against backgroundColor\n" +
                "5. accentColor must POP and be clearly different from other colors\n" +
                "6. All colors must be bold, saturated, and easy to distinguish\n\n" +
                "Examples:\n" +
                "- 'summer beach' → bright orange/yellow background, dark blue text, coral buttons\n" +
                "- 'dark cyberpunk' → black background, neon green text, purple buttons\n\n" +
                "Return ONLY valid JSON (no markdown):\n" +
                "{\"backgroundColor\":\"#XXXXXX\",\"textColor\":\"#XXXXXX\",\"accentColor\":\"#XXXXXX\",\"buttonColor\":\"#XXXXXX\",\"toolbarColor\":\"#XXXXXX\"}";

        Content content = new Content.Builder().addText(createPrompt).build();

        ListenableFuture<GenerateContentResponse> futureResponse = model.generateContent(content);

        Futures.addCallback(futureResponse, new FutureCallback<>() {
            /**
             * Called when Gemini API successfully returns a theme.
             * Cleans markdown formatting, parses JSON response, and invokes callback.
             * @param result Response containing JSON theme specification
             */
            @Override
            public void onSuccess(GenerateContentResponse result) {
                try {
                    ThemeSpec theme = GeminiJson.parse(result.getText(), ThemeSpec.class);
                    if (theme == null) {
                        callback.onError(new Exception("Empty theme response"));
                        return;
                    }
                    callback.onThemeGenerated(theme);
                } catch (Exception e) {
                    Log.e(TAG, "Failed to parse theme JSON", e);
                    callback.onError(e);
                }
            }
            /**
             * Called when Gemini API request fails.
             * Handles network errors, API failures, and parsing issues.
             * @param t Throwable describing the failure cause
             */
            @Override
            public void onFailure(Throwable t) {
                Log.e(TAG, "Failed to generate theme", t);
                callback.onError(new Exception(t));
            }
        }, MoreExecutors.directExecutor());

    }

}
