package com.weatherplanner.app;

import com.google.ai.client.generativeai.GenerativeModel;
import com.google.ai.client.generativeai.java.GenerativeModelFutures;
import com.google.ai.client.generativeai.type.Content;
import com.google.ai.client.generativeai.type.GenerateContentResponse;
import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.MoreExecutors;
import com.google.gson.annotations.SerializedName;

import android.util.Log;

import java.util.Arrays;
import java.util.List;

/**
 * WeatherInsightsGenerator is a utility class that uses Gemini LLM to generate
 * context-relevant weather questions and answers based on current weather data.
 *
 * This class provides two main functionalities:
 * 1. Generate weather-related questions that users might ask
 * 2. Generate answers to those questions based on weather conditions
 *
 * Usage pattern follows ThemeGenerator with async callbacks.
 */
public class WeatherInsightsGenerator {
    private static final String TAG = "WeatherInsightsGenerator";

    /**
     * Data class representing weather-related questions generated by LLM.
     * Contains a list of question strings that will be displayed as buttons.
     */
    public static class QuestionSet {
        @SerializedName("questions")
        public List<String> questions;
    }

    /**
     * Data class representing an answer to a weather question.
     * Contains the answer text generated by LLM.
     */
    public static class Answer {
        @SerializedName("answer")
        public String answer;
    }

    /**
     * Callback interface for asynchronous question generation.
     */
    public interface QuestionCallback {
        /**
         * Called when questions are successfully generated.
         * @param questions The set of generated questions
         */
        void onQuestionsGenerated(QuestionSet questions);

        /**
         * Called when question generation fails.
         * @param e The exception that occurred
         */
        void onError(Exception e);
    }

    /**
     * Callback interface for asynchronous answer generation.
     */
    public interface AnswerCallback {
        /**
         * Called when an answer is successfully generated.
         * @param answer The generated answer
         */
        void onAnswerGenerated(Answer answer);

        /**
         * Called when answer generation fails.
         * @param e The exception that occurred
         */
        void onError(Exception e);
    }

    /**
     * Generates weather-related questions based on current weather conditions.
     * The LLM will create context-specific questions that help users make decisions.
     *
     * @param apiKey Gemini API key for authentication
     * @param cityName Name of the city
     * @param temperature Current temperature (e.g., "72°F" or "22°C")
     * @param weatherCondition Weather condition (e.g., "Sunny", "Rainy", "Cloudy")
     * @param humidity Humidity percentage (e.g., "65%")
     * @param windCondition Wind condition (e.g., "15 mph NE")
     * @param callback Callback to receive generated questions or error
     */
    public static void generateQuestions(
            String apiKey,
            String cityName,
            String temperature,
            String weatherCondition,
            String humidity,
            String windCondition,
            QuestionCallback callback
    ) {
        // Validate API key
        if (apiKey == null || apiKey.isEmpty()) {
            Log.w(TAG, "API key missing; returning demo weather questions.");
            QuestionSet fallback = new QuestionSet();
            fallback.questions = Arrays.asList(
                    "What should I wear today?",
                    "Is this good weather for outdoor plans?",
                    "Should I expect travel delays?"
            );
            callback.onQuestionsGenerated(fallback);
            return;
        }

        // Initialize Gemini model
        GenerativeModel gm = new GenerativeModel(GeminiModels.FAST_TEXT_MODEL, apiKey);
        GenerativeModelFutures model = GenerativeModelFutures.from(gm);

        // Construct the prompt for question generation
        String prompt = "You are a helpful weather assistant. Based on the following weather data, " +
                "generate exactly 3 practical, context-specific questions that a user in " + cityName +
                " might ask to help them plan their day.\n\n" +
                "WEATHER DATA:\n" +
                "- City: " + cityName + "\n" +
                "- Temperature: " + temperature + "\n" +
                "- Condition: " + weatherCondition + "\n" +
                "- Humidity: " + humidity + "\n" +
                "- Wind: " + windCondition + "\n\n" +
                "REQUIREMENTS:\n" +
                "1. Questions must be practical and actionable\n" +
                "2. Questions should relate directly to the weather conditions\n" +
                "3. Keep questions concise (under 15 words each)\n" +
                "4. Focus on daily activities (clothing, outdoor plans, transportation, etc.)\n\n" +
                "EXAMPLES:\n" +
                "- If it's rainy: \"Should I bring an umbrella?\", \"Is it safe to drive?\"\n" +
                "- If it's hot: \"What should I wear to stay cool?\", \"Should I stay hydrated?\"\n" +
                "- If it's cold: \"Do I need a heavy jacket?\", \"Will my car need to warm up?\"\n\n" +
                "Return ONLY valid JSON (no markdown, no code blocks):\n" +
                "{\"questions\": [\"question 1\", \"question 2\", \"question 3\"]}";

        // Create content and send request
        Content content = new Content.Builder().addText(prompt).build();
        ListenableFuture<GenerateContentResponse> futureResponse = model.generateContent(content);

        // Handle async response
        Futures.addCallback(futureResponse, new FutureCallback<GenerateContentResponse>() {
            /**
             * Called when Gemini successfully generates questions.
             * Cleans markdown, parses JSON, validates questions, and invokes callback.
             * @param result Response containing JSON with list of questions
             */
            @Override
            public void onSuccess(GenerateContentResponse result) {
                try {
                    QuestionSet questions = GeminiJson.parse(result.getText(), QuestionSet.class);

                    // Validate that we got questions
                    if (questions == null || questions.questions == null ||
                            questions.questions.isEmpty()) {
                        Log.e(TAG, "No questions generated or invalid format");
                        callback.onError(new Exception("No questions generated"));
                        return;
                    }

                    callback.onQuestionsGenerated(questions);
                } catch (Exception e) {
                    Log.e(TAG, "Failed to parse questions JSON", e);
                    callback.onError(e);
                }
            }

            /**
             * Called when Gemini API fails to generate questions.
             * Handles network errors, API failures, and timeouts.
             * @param t Throwable describing the failure cause
             */
            @Override
            public void onFailure(Throwable t) {
                Log.e(TAG, "Failed to generate questions", t);
                callback.onError(new Exception(t));
            }
        }, MoreExecutors.directExecutor());
    }

    /**
     * Generates an answer to a specific weather-related question.
     * The answer will be personalized based on the current weather conditions.
     *
     * @param apiKey Gemini API key for authentication
     * @param cityName Name of the city
     * @param temperature Current temperature
     * @param weatherCondition Weather condition
     * @param humidity Humidity percentage
     * @param windCondition Wind condition
     * @param question The question to answer
     * @param callback Callback to receive generated answer or error
     */
    public static void generateAnswer(
            String apiKey,
            String cityName,
            String temperature,
            String weatherCondition,
            String humidity,
            String windCondition,
            String question,
            AnswerCallback callback
    ) {
        // Validate API key
        if (apiKey == null || apiKey.isEmpty()) {
            Log.w(TAG, "API key missing; returning demo weather answer.");
            Answer fallback = new Answer();
            fallback.answer = "Demo mode is using local weather guidance because no Gemini API key is configured. Based on the current conditions, plan for comfortable weather, check the forecast before leaving, and adjust clothing or activities if conditions change.";
            callback.onAnswerGenerated(fallback);
            return;
        }

        // Initialize Gemini model
        GenerativeModel gm = new GenerativeModel(GeminiModels.FAST_TEXT_MODEL, apiKey);
        GenerativeModelFutures model = GenerativeModelFutures.from(gm);

        // Construct the prompt for answer generation
        String prompt = "You are a helpful weather assistant. Answer the following question based on " +
                "the current weather conditions in " + cityName + ".\n\n" +
                "WEATHER DATA:\n" +
                "- City: " + cityName + "\n" +
                "- Temperature: " + temperature + "\n" +
                "- Condition: " + weatherCondition + "\n" +
                "- Humidity: " + humidity + "\n" +
                "- Wind: " + windCondition + "\n\n" +
                "QUESTION: " + question + "\n\n" +
                "REQUIREMENTS:\n" +
                "1. Provide a direct, practical answer (2-4 sentences)\n" +
                "2. Reference specific weather data in your answer\n" +
                "3. Give actionable advice when relevant\n" +
                "4. Be friendly and conversational\n" +
                "5. If the question asks about clothing, be specific about what to wear\n" +
                "6. If the question asks about activities, suggest alternatives if needed\n\n" +
                "Return ONLY valid JSON (no markdown, no code blocks):\n" +
                "{\"answer\": \"your answer here\"}";

        // Create content and send request
        Content content = new Content.Builder().addText(prompt).build();
        ListenableFuture<GenerateContentResponse> futureResponse = model.generateContent(content);

        // Handle async response
        Futures.addCallback(futureResponse, new FutureCallback<GenerateContentResponse>() {
            /**
             * Called when Gemini successfully generates an answer.
             * Cleans markdown, parses JSON, validates answer text, and invokes callback.
             * @param result Response containing JSON with answer text
             */
            @Override
            public void onSuccess(GenerateContentResponse result) {
                try {
                    Answer answer = GeminiJson.parse(result.getText(), Answer.class);

                    // Validate that we got an answer
                    if (answer == null || answer.answer == null || answer.answer.isEmpty()) {
                        Log.e(TAG, "No answer generated or invalid format");
                        callback.onError(new Exception("No answer generated"));
                        return;
                    }

                    callback.onAnswerGenerated(answer);
                } catch (Exception e) {
                    Log.e(TAG, "Failed to parse answer JSON", e);
                    callback.onError(e);
                }
            }

            /**
             * Called when Gemini API fails to generate an answer.
             * Handles network errors, API failures, and timeouts.
             * @param t Throwable describing the failure cause
             */
            @Override
            public void onFailure(Throwable t) {
                Log.e(TAG, "Failed to generate answer", t);
                callback.onError(new Exception(t));
            }
        }, MoreExecutors.directExecutor());
    }
}
